baseURL = "https://its-rajesh.github.io/dharmicwaves/"
languageCode = "en-us"
title = "Dharmic Waves"
theme = "LoveIt"
description = "My blog on music, mind, and the multiverse"

[params]
  defaultTheme = "auto"
  enableGitInfo = true
  googleAnalytics = "G-4WN5JB33EB"
  logo = "/dharmicwaves/images/logo.png"
  ShowSocialIcons = true

[params.author]
  name = "Rajesh"

[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"

  [params.header.title]
    logo = "/dharmicwaves/images/logo.png"
    name = "Dharmic Waves"

[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/dharmicwaves/images/avatar.png"
    title = "Dharmic Waves"
    subtitle = "Intuition, Science, Politics, Nation, and Beyond!"
    typeit = true
    social = true

[params.page]
  [params.page.share]
    enable = false
  [params.page.social]
    enable = false


[params.social]
  Instagram = "/dharmicwaves/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
