baseURL = "https://its-rajesh.github.io/dharmicwaves/"
languageCode = "en-us"
theme = "LoveIt"
title = "Dharmic Waves"
description = "My blog on music, mind, and the multiverse"

[params]
  defaultTheme = "auto"
  enableGitInfo = true
  title = "Dharmic Waves"
  description = "Reflections at the intersection of dharma, signal processing, and code"
  googleAnalytics = "G-4WN5JB33EB"

[params.header]
  title = "Dharmic Waves"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
