baseURL = "https://its-rajesh.github.io/dharmicwaves/"
languageCode = "en-us"
title = "Dharmic Waves"
theme = "LoveIt"
description = "My blog on music, mind, and the multiverse"

[params.home.profile]
  enable = true
  avatarURL = "/images/avatar.png"    # optional
  title = "Dharmic Waves"             # optional
  subtitle = "Reflections at the intersection of dharma, signal processing, and code"
  typeit = true
  social = true

[params]
  defaultTheme = "auto"
  enableGitInfo = true
  googleAnalytics = "G-4WN5JB33EB"

[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"

  [params.header.title]
    logo = "images/logo.png"
    name = "Dharmic Waves"
    # optional: pre/post/typeit attributed to the theme :contentReference[oaicite:6]{index=6}

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
