baseURL = "https://its-rajesh.github.io/dharmicwaves/"
languageCode = "en-us"
theme = "LoveIt"
title = "Dharmic Waves"
description = "My blog on music, mind, and the multiverse"


[params]
  defaultTheme = "auto"
  enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
