baseURL = "https://its-rajesh.github.io/dharmicwaves/"
languageCode = "en-us"
title = "Dharmic Waves"
theme = "LoveIt"
description = "My blog on music, mind, and the multiverse"

[params]
  title = "Dharmic Waves"
  description = "Reflections at the intersection of dharma, signal processing, and code"
  defaultTheme = "auto"
  enableGitInfo = true
  googleAnalytics = "G-4WN5JB33EB"
  logo = ""

[params.header]
  title = "Dharmic Waves"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

